export const { NEXT_PUBLIC_ARTSFLOW_URL: ARTSFLOW_URL } = process.env
export const { NEXT_PUBLIC_GCP_MAPS_KEY: GCP_MAPS_KEY } = process.env
export const { NEXT_PUBLIC_FIREBASE_API_KEY: FIREBASE_API_KEY } = process.env
export const { NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: FIREBASE_AUTH_DOMAIN } = process.env
export const { NEXT_PUBLIC_FIREBASE_PROJECT_ID: FIREBASE_PROJECT_ID } = process.env
export const { NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: FIREBASE_STORAGE_BUCKET } = process.env
export const {
  NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: FIREBASE_MESSAGING_SENDER_ID,
} = process.env
export const { NEXT_PUBLIC_FIREBASE_APP_ID: FIREBASE_APP_ID } = process.env
export const { NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID: FIREBASE_MEASUREMENT_ID } = process.env
export const { NEXT_PUBLIC_STRIPE_KEY: STRIPE_KEY } = process.env
